# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
#from PyQt5.QtWidgets import QApplication, QMainWindow


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1013, 977)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/assets/images/icon.png"),
                       QtGui.QIcon.Normal,
                       QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_user_mode = QtWidgets.QHBoxLayout()
        self.horizontalLayout_user_mode.setSizeConstraint(QtWidgets.
                                                          QLayout.
                                                          SetFixedSize)
        self.horizontalLayout_user_mode.setObjectName("horizontalLayout_user_mode")
        self.users_box = QtWidgets.QGroupBox(self.centralwidget)
        self.users_box.setMinimumSize(QtCore.QSize(200, 200))
        self.users_box.setMaximumSize(QtCore.QSize(300, 250))
        self.users_box.setObjectName("users_box")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.users_box)
        self.verticalLayout.setObjectName("verticalLayout")
        self.signin = QtWidgets.QPushButton(self.users_box)
        self.signin.setObjectName("signin")
        self.verticalLayout.addWidget(self.signin)
        self.signup = QtWidgets.QPushButton(self.users_box)
        self.signup.setObjectName("signup")
        self.verticalLayout.addWidget(self.signup)
        self.horizontalLayout_user_mode.addWidget(self.users_box)
        self.substitute_mode_box = QtWidgets.QGroupBox(self.centralwidget)
        self.substitute_mode_box.setMinimumSize(QtCore.QSize(200, 200))
        self.substitute_mode_box.setMaximumSize(QtCore.QSize(300, 250))
        self.substitute_mode_box.setObjectName("substitute_mode_box")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.substitute_mode_box)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.openfoodfacts_mode = QtWidgets.QPushButton(self.substitute_mode_box)
        self.openfoodfacts_mode.setEnabled(True)
        self.openfoodfacts_mode.setCheckable(True)
        self.openfoodfacts_mode.setChecked(False)
        self.openfoodfacts_mode.setAutoDefault(False)
        self.openfoodfacts_mode.setDefault(False)
        self.openfoodfacts_mode.setFlat(False)
        self.openfoodfacts_mode.setObjectName("openfoodfacts_mode")
        self.verticalLayout_2.addWidget(self.openfoodfacts_mode)
        self.local_mode = QtWidgets.QPushButton(self.substitute_mode_box)
        self.local_mode.setCheckable(True)
        self.local_mode.setObjectName("local_mode")
        self.verticalLayout_2.addWidget(self.local_mode)
        self.horizontalLayout_user_mode.addWidget(self.substitute_mode_box)
        self.verticalLayout_6.addLayout(self.horizontalLayout_user_mode)
        self.search_splitter = QtWidgets.QSplitter(self.centralwidget)
        self.search_splitter.setOrientation(QtCore.Qt.Horizontal)
        self.search_splitter.setObjectName("search_splitter")
        self.categories_grp = QtWidgets.QGroupBox(self.search_splitter)
        self.categories_grp.setObjectName("categories_grp")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.categories_grp)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.categories_list = QtWidgets.QListWidget(self.categories_grp)
        self.categories_list.setObjectName("categories_list")
        self.verticalLayout_4.addWidget(self.categories_list)
        self.foods_grp = QtWidgets.QGroupBox(self.search_splitter)
        self.foods_grp.setObjectName("foods_grp")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.foods_grp)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.foods_list = QtWidgets.QListView(self.foods_grp)
        self.foods_list.setObjectName("foods_list")
        self.verticalLayout_3.addWidget(self.foods_list)
        self.substitute_result_grp = QtWidgets.QGroupBox(self.search_splitter)
        self.substitute_result_grp.setObjectName("substitute_result_grp")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.substitute_result_grp)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.substitute_widget = QtWidgets.QWidget(self.substitute_result_grp)
        self.substitute_widget.setObjectName("substitute_widget")
        self.formLayout = QtWidgets.QFormLayout(self.substitute_widget)
        self.formLayout.setObjectName("formLayout")
        self.label_nom = QtWidgets.QLabel(self.substitute_widget)
        self.label_nom.setObjectName("label_nom")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_nom)
        self.substitute_name = QtWidgets.QLineEdit(self.substitute_widget)
        self.substitute_name.setReadOnly(True)
        self.substitute_name.setObjectName("substitute_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.substitute_name)
        self.label_description = QtWidgets.QLabel(self.substitute_widget)
        self.label_description.setObjectName("label_description")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_description)
        self.label_shops = QtWidgets.QLabel(self.substitute_widget)
        self.label_shops.setObjectName("label_shops")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_shops)
        self.substitute_shops = QtWidgets.QListView(self.substitute_widget)
        self.substitute_shops.setObjectName("substitute_shops")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.substitute_shops)
        self.substitute_description = QtWidgets.QTextEdit(self.substitute_widget)
        self.substitute_description.setAutoFillBackground(False)
        self.substitute_description.setReadOnly(True)
        self.substitute_description.setObjectName("substitute_description")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.substitute_description)
        self.record = QtWidgets.QPushButton(self.substitute_widget)
        self.record.setEnabled(False)
        self.record.setObjectName("record")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.record)
        self.verticalLayout_5.addWidget(self.substitute_widget)
        self.verticalLayout_6.addWidget(self.search_splitter)
        self.quit = QtWidgets.QPushButton(self.centralwidget)
        self.quit.setObjectName("quit")
        self.verticalLayout_6.addWidget(self.quit)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "OpenFoodFacts Food Substitutions (OpeClassRooms projet-5)"))
        self.users_box.setTitle(_translate("MainWindow", "Utilisateur"))
        self.signin.setText(_translate("MainWindow", "Sign-in"))
        self.signup.setText(_translate("MainWindow", "Sign-up"))
        self.substitute_mode_box.setTitle(_translate("MainWindow", "Reherche de substitution d\'aliment"))
        self.openfoodfacts_mode.setText(_translate("MainWindow", "List OpenFoodFacts"))
        self.local_mode.setText(_translate("MainWindow", "Liste locale"))
        self.categories_grp.setTitle(_translate("MainWindow", "Sélectionnez une catégorie"))
        self.foods_grp.setTitle(_translate("MainWindow", "Sélectionnez un aliment"))
        self.substitute_result_grp.setTitle(_translate("MainWindow", "Substitutions proposée"))
        self.label_nom.setText(_translate("MainWindow", "Nom"))
        self.label_description.setText(_translate("MainWindow", "Description"))
        self.label_shops.setText(_translate("MainWindow", "Magasins"))
        self.record.setText(_translate("MainWindow", "Enregistrer dans ma base"))
        self.quit.setText(_translate("MainWindow", "Quitter"))


import ui.images_rc
