# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1013, 977)
        MainWindow.setMinimumSize(QtCore.QSize(800, 800))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/assets/images/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_user_mode = QtWidgets.QHBoxLayout()
        self.horizontalLayout_user_mode.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_user_mode.setObjectName("horizontalLayout_user_mode")
        self.users_box = QtWidgets.QGroupBox(self.centralwidget)
        self.users_box.setMinimumSize(QtCore.QSize(200, 200))
        self.users_box.setMaximumSize(QtCore.QSize(300, 250))
        self.users_box.setObjectName("users_box")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.users_box)
        self.verticalLayout.setObjectName("verticalLayout")
        self.signin = QtWidgets.QPushButton(self.users_box)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        self.signin.setFont(font)
        self.signin.setObjectName("signin")
        self.verticalLayout.addWidget(self.signin)
        self.signup = QtWidgets.QPushButton(self.users_box)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        self.signup.setFont(font)
        self.signup.setObjectName("signup")
        self.verticalLayout.addWidget(self.signup)
        self.frame_2 = QtWidgets.QFrame(self.users_box)
        self.frame_2.setStyleSheet("border-image: url(:/images/assets/images/home 1.png);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout.addWidget(self.frame_2)
        self.horizontalLayout_user_mode.addWidget(self.users_box)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(250, 150))
        self.frame.setStyleSheet("border-image: url(:/images/assets/images/openfoodfacts+oc.png);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_user_mode.addWidget(self.frame)
        self.substitute_mode_box = QtWidgets.QGroupBox(self.centralwidget)
        self.substitute_mode_box.setMinimumSize(QtCore.QSize(200, 200))
        self.substitute_mode_box.setMaximumSize(QtCore.QSize(300, 250))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(11)
        font.setUnderline(True)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.substitute_mode_box.setFont(font)
        self.substitute_mode_box.setObjectName("substitute_mode_box")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.substitute_mode_box)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.openfoodfacts_mode = QtWidgets.QPushButton(self.substitute_mode_box)
        self.openfoodfacts_mode.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openfoodfacts_mode.sizePolicy().hasHeightForWidth())
        self.openfoodfacts_mode.setSizePolicy(sizePolicy)
        self.openfoodfacts_mode.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.openfoodfacts_mode.setFont(font)
        self.openfoodfacts_mode.setIcon(icon)
        self.openfoodfacts_mode.setCheckable(True)
        self.openfoodfacts_mode.setChecked(False)
        self.openfoodfacts_mode.setAutoDefault(False)
        self.openfoodfacts_mode.setDefault(False)
        self.openfoodfacts_mode.setFlat(False)
        self.openfoodfacts_mode.setObjectName("openfoodfacts_mode")
        self.verticalLayout_2.addWidget(self.openfoodfacts_mode)
        self.local_mode = QtWidgets.QPushButton(self.substitute_mode_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.local_mode.sizePolicy().hasHeightForWidth())
        self.local_mode.setSizePolicy(sizePolicy)
        self.local_mode.setMinimumSize(QtCore.QSize(0, 0))
        self.local_mode.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.local_mode.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/assets/images/home 1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.local_mode.setIcon(icon1)
        self.local_mode.setCheckable(True)
        self.local_mode.setObjectName("local_mode")
        self.verticalLayout_2.addWidget(self.local_mode)
        self.horizontalLayout_user_mode.addWidget(self.substitute_mode_box)
        self.verticalLayout_7.addLayout(self.horizontalLayout_user_mode)
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.categories_grp = QtWidgets.QGroupBox(self.splitter_2)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(11)
        font.setUnderline(True)
        self.categories_grp.setFont(font)
        self.categories_grp.setObjectName("categories_grp")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.categories_grp)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.categories_list = QtWidgets.QListView(self.categories_grp)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        font.setUnderline(False)
        self.categories_list.setFont(font)
        self.categories_list.setObjectName("categories_list")
        self.verticalLayout_4.addWidget(self.categories_list)
        self.foods_grp = QtWidgets.QGroupBox(self.splitter_2)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(11)
        font.setUnderline(True)
        self.foods_grp.setFont(font)
        self.foods_grp.setObjectName("foods_grp")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.foods_grp)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.foods_list = QtWidgets.QListView(self.foods_grp)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        font.setUnderline(False)
        self.foods_list.setFont(font)
        self.foods_list.setObjectName("foods_list")
        self.verticalLayout_3.addWidget(self.foods_list)
        self.groupBox = QtWidgets.QGroupBox(self.splitter_2)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(11)
        font.setUnderline(True)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.splitter = QtWidgets.QSplitter(self.groupBox)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.substitutes_list = QtWidgets.QTableView(self.splitter)
        self.substitutes_list.setObjectName("substitutes_list")
        self.substitute_selected_grp = QtWidgets.QGroupBox(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(11)
        font.setUnderline(True)
        self.substitute_selected_grp.setFont(font)
        self.substitute_selected_grp.setObjectName("substitute_selected_grp")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.substitute_selected_grp)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.substitute_widget = QtWidgets.QWidget(self.substitute_selected_grp)
        self.substitute_widget.setObjectName("substitute_widget")
        self.formLayout = QtWidgets.QFormLayout(self.substitute_widget)
        self.formLayout.setObjectName("formLayout")
        self.label_nom = QtWidgets.QLabel(self.substitute_widget)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        font.setUnderline(False)
        self.label_nom.setFont(font)
        self.label_nom.setObjectName("label_nom")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_nom)
        self.substitute_name = QtWidgets.QLineEdit(self.substitute_widget)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        font.setUnderline(False)
        self.substitute_name.setFont(font)
        self.substitute_name.setReadOnly(True)
        self.substitute_name.setObjectName("substitute_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.substitute_name)
        self.label_description = QtWidgets.QLabel(self.substitute_widget)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        font.setUnderline(False)
        self.label_description.setFont(font)
        self.label_description.setObjectName("label_description")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_description)
        self.label_shops = QtWidgets.QLabel(self.substitute_widget)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        font.setUnderline(False)
        self.label_shops.setFont(font)
        self.label_shops.setObjectName("label_shops")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_shops)
        self.substitute_description = QtWidgets.QTextEdit(self.substitute_widget)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        font.setUnderline(False)
        self.substitute_description.setFont(font)
        self.substitute_description.setAutoFillBackground(False)
        self.substitute_description.setReadOnly(True)
        self.substitute_description.setObjectName("substitute_description")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.substitute_description)
        self.label_url = QtWidgets.QLabel(self.substitute_widget)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        font.setUnderline(False)
        self.label_url.setFont(font)
        self.label_url.setObjectName("label_url")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_url)
        self.substitute_url = QtWidgets.QLineEdit(self.substitute_widget)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        font.setUnderline(False)
        self.substitute_url.setFont(font)
        self.substitute_url.setReadOnly(True)
        self.substitute_url.setObjectName("substitute_url")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.substitute_url)
        self.label_score = QtWidgets.QLabel(self.substitute_widget)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        font.setUnderline(False)
        self.label_score.setFont(font)
        self.label_score.setObjectName("label_score")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_score)
        self.substitute_score = QtWidgets.QLineEdit(self.substitute_widget)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        font.setUnderline(False)
        self.substitute_score.setFont(font)
        self.substitute_score.setReadOnly(True)
        self.substitute_score.setObjectName("substitute_score")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.substitute_score)
        self.substitute_shops = QtWidgets.QListView(self.substitute_widget)
        self.substitute_shops.setObjectName("substitute_shops")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.substitute_shops)
        self.verticalLayout_5.addWidget(self.substitute_widget)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.verticalLayout_6.addWidget(self.splitter)
        self.record = QtWidgets.QPushButton(self.groupBox)
        self.record.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.record.setFont(font)
        self.record.setObjectName("record")
        self.verticalLayout_6.addWidget(self.record)
        self.verticalLayout_7.addWidget(self.splitter_2)
        self.quit = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        font.setUnderline(False)
        self.quit.setFont(font)
        self.quit.setObjectName("quit")
        self.verticalLayout_7.addWidget(self.quit)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "OpenFoodFacts Food Substitutions (OpeClassRooms projet-5)"))
        self.users_box.setTitle(_translate("MainWindow", "Utilisateur"))
        self.signin.setText(_translate("MainWindow", "Sign-in"))
        self.signup.setText(_translate("MainWindow", "Sign-up"))
        self.substitute_mode_box.setTitle(_translate("MainWindow", "Reherche de substitution d\'aliment"))
        self.openfoodfacts_mode.setText(_translate("MainWindow", "List OpenFoodFacts"))
        self.local_mode.setText(_translate("MainWindow", "Liste locale"))
        self.categories_grp.setTitle(_translate("MainWindow", "Sélectionnez une catégorie"))
        self.foods_grp.setTitle(_translate("MainWindow", "Sélectionnez un aliment"))
        self.groupBox.setTitle(_translate("MainWindow", "Substituts proposés"))
        self.substitute_selected_grp.setTitle(_translate("MainWindow", "Détails"))
        self.label_nom.setText(_translate("MainWindow", "Nom"))
        self.label_description.setText(_translate("MainWindow", "Description"))
        self.label_shops.setText(_translate("MainWindow", "Magasins"))
        self.label_url.setText(_translate("MainWindow", "url"))
        self.label_score.setText(_translate("MainWindow", "Score"))
        self.record.setText(_translate("MainWindow", "Enregistrer dans ma base"))
        self.quit.setText(_translate("MainWindow", "Quitter"))


import ui.images_rc
