# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sign-up.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SignUp(object):
    def setupUi(self, SignUp):
        SignUp.setObjectName("SignUp")
        SignUp.resize(600, 300)
        SignUp.setMinimumSize(QtCore.QSize(450, 300))
        SignUp.setMaximumSize(QtCore.QSize(600, 400))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/assets/images/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SignUp.setWindowIcon(icon)
        SignUp.setStyleSheet("")
        self.verticalLayout = QtWidgets.QVBoxLayout(SignUp)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_nickname = QtWidgets.QLabel(SignUp)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(9)
        self.label_nickname.setFont(font)
        self.label_nickname.setObjectName("label_nickname")
        self.gridLayout.addWidget(self.label_nickname, 0, 0, 1, 1)
        self.nickname = QtWidgets.QLineEdit(SignUp)
        self.nickname.setObjectName("nickname")
        self.gridLayout.addWidget(self.nickname, 0, 1, 1, 1)
        self.password = QtWidgets.QLineEdit(SignUp)
        self.password.setObjectName("password")
        self.gridLayout.addWidget(self.password, 3, 1, 1, 1)
        self.label_username = QtWidgets.QLabel(SignUp)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(9)
        self.label_username.setFont(font)
        self.label_username.setObjectName("label_username")
        self.gridLayout.addWidget(self.label_username, 2, 0, 1, 1)
        self.label_password = QtWidgets.QLabel(SignUp)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(9)
        self.label_password.setFont(font)
        self.label_password.setObjectName("label_password")
        self.gridLayout.addWidget(self.label_password, 3, 0, 1, 1)
        self.label_familyname = QtWidgets.QLabel(SignUp)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(9)
        self.label_familyname.setFont(font)
        self.label_familyname.setObjectName("label_familyname")
        self.gridLayout.addWidget(self.label_familyname, 1, 0, 1, 1)
        self.familyname = QtWidgets.QLineEdit(SignUp)
        self.familyname.setObjectName("familyname")
        self.gridLayout.addWidget(self.familyname, 1, 1, 1, 1)
        self.username = QtWidgets.QLineEdit(SignUp)
        self.username.setObjectName("username")
        self.gridLayout.addWidget(self.username, 2, 1, 1, 1)
        self.passwd_confirm = QtWidgets.QLineEdit(SignUp)
        self.passwd_confirm.setObjectName("passwd_confirm")
        self.gridLayout.addWidget(self.passwd_confirm, 4, 1, 1, 1)
        self.label = QtWidgets.QLabel(SignUp)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 4, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.frame = QtWidgets.QFrame(SignUp)
        self.frame.setStyleSheet("border-image: url(:/images/assets/images/sign_in_localDB_openfoodfacts.png);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 135, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.verticalLayout.addWidget(self.frame)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.status = QtWidgets.QLabel(SignUp)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.status.setFont(font)
        self.status.setText("")
        self.status.setObjectName("status")
        self.horizontalLayout.addWidget(self.status)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.record = QtWidgets.QPushButton(SignUp)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.record.setFont(font)
        self.record.setObjectName("record")
        self.horizontalLayout.addWidget(self.record)
        self.cancel = QtWidgets.QPushButton(SignUp)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cancel.setFont(font)
        self.cancel.setObjectName("cancel")
        self.horizontalLayout.addWidget(self.cancel)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(SignUp)
        QtCore.QMetaObject.connectSlotsByName(SignUp)

    def retranslateUi(self, SignUp):
        _translate = QtCore.QCoreApplication.translate
        SignUp.setWindowTitle(_translate("SignUp", "S\'enregistrer sur la base de donnée locale"))
        self.label_nickname.setText(_translate("SignUp", "Prénom"))
        self.label_username.setText(_translate("SignUp", "Nom d\'utilisateur"))
        self.label_password.setText(_translate("SignUp", "Mot de passe"))
        self.label_familyname.setText(_translate("SignUp", "Nom de famille"))
        self.label.setText(_translate("SignUp", "Confirmer mot de passe"))
        self.record.setText(_translate("SignUp", "S\'enregistrer"))
        self.cancel.setText(_translate("SignUp", "Annuler"))


import ui.images_rc
